version: '3'
services:
  graphite:
    image: hopsoft/graphite-statsd
    container_name: graphite
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    restart: always
  cassandra-0:
    image: custom_cassandra
    build: .
    container_name: cassandra-0
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-0"
    ports:
    - 7000
    restart: always
    depends_on:
      - graphite
  cassandra-1:
    image: custom_cassandra
    build: .
    container_name: cassandra-1
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-1"
      CASSANDRA_SEEDS: "cassandra-0"
    ports:
    - 7000
    restart: always
    depends_on:
      - graphite
      - cassandra-0
  cassandra-2:
    image: custom_cassandra
    build: .
    container_name: cassandra-2
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-2"
      CASSANDRA_SEEDS: "cassandra-0"
    ports:
    - 7000
    restart: always
    depends_on:
      - graphite
      - cassandra-1
