version: '3'
services:
  cassandra-0:
    image: cassandra_custom
    build: .
    container_name: cassandra-0
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-0"
    networks:
      - monitoringstack_backend_bridge
    restart: always
  cassandra-1:
    image: cassandra_custom
    build: .
    container_name: cassandra-1
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-1"
      CASSANDRA_SEEDS: "cassandra-0"
    networks:
      - monitoringstack_backend_bridge
    restart: always
    depends_on:
      - cassandra-0
  cassandra-2:
    image: cassandra_custom
    build: .
    container_name: cassandra-2
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-2"
      CASSANDRA_SEEDS: "cassandra-0"
    networks:
      - monitoringstack_backend_bridge
    restart: always
    depends_on:
      - cassandra-1

networks:
  monitoringstack_backend_bridge:
    external: true
